print("Olá turma do Python!")
print("Tudo bem!")
nome: str = input("Qual é o seu nome? ")
print(f"Olá, {nome}!") 
idade: str = input("Qual a tua idade? ")
print(f"Idade, {idade}")
genero: str = input("Qual o teu gênero? ")
print(f"gênero, {genero}")
cidade: str = input("De qual cidade você é? ")
print(f"Cidade: {cidade}")
print("Obrigado por compartilhar essas informações! :)")
